### DISCUSSION TITLE
1.24 [12.09.2022]

### DISCUSSION THREAD

**Discussion by sbrunner** [sbrunner/scan-to-paperless#744] [Announcements]
# What's new in version 1.24

* Use [`pngquant`](https://pngquant.org/) instead of JPEG
* Add QR code content
* Support of double-sided roller scanner

# Use [`pngquant`](https://pngquant.org/) instead of JPEG

In version 1.23 we use `exiftool` to optimize the PDF, but it sometimes transforms the images in ugly JPEG.
In version 1.24 we can use `pngquant` to quantize the PNG.

By default, none of them are activated, to activate pngquant, use the `args` `run_exiftool` and set it to `true`.
To use pngquant set the `args` `run_pngquant` to `true`, you can also add `pngquant_options`, by default 
it uses: `["--skip-if-larger", "--speed=1", "--strip", "--quality=0-32"]`.

# Add QR code content

In version 2.14 a new page is added at the end of your PDF with the content of all the detected codes.
You can use all the environment variable that starts with `SCAN_CODES_` to configure it, see the `README.md`.

And to be able to scan the (QR)Codes from other sources, I add a new folder `/scan-codes`.

Note that in the QRbill there are some important empty lines, that didn't work with PDF copy, then I add a pipe in those lines, and
you can run `scan --convert-clipboard` that will scan your clipboard to do the inverse transform.

# Support of double-sided roller scanner

I buy a new scanner: [HP Scanjet Pro 2000 s2](https://www.hp.com/fr-fr/shop/product.aspx?id=6FW06A&opt=B19&sel=SCN)
And it didn't work out of the box, then I do the following changes:
- Be able to scan to a tiff file (directly get the DPI from the TIFF file).
- Be able to use the double side mode.
- Be able to have a non-white background.

The configuration I use with my new scanner:
```yaml
scanimage_arguments:
  # scanimage --list-devices
  - --device=airscan:e0:HP ScanJet Pro 2000 s2 (USB)
  - --format=tiff
  - --mode=color
  # 75|150|200|240|300|400|500|600
  - --resolution=400
  - -y
  - '309'

# New option
type: tiff

# New section
modes:
  adf:
    scanimage_arguments:
      - --source=ADF
  double:
    scanimage_arguments:
      - --source=ADF Duplex
    auto_bash: false
    rotate_even: false
  one:
    scanimage_arguments:
      - --source=ADF
      - --batch-count=1

default_args:
  # New Arguments
  auto_mask: {}
  auto_cut: {}
  run_pngquant: true
  cut_white: 200
  
  # The DPI isn't required anymore with TIFF files
```
# Other changes

* Update the deskew and add new option and debug images
* The Creator metadata is fill with the Scan to Paperless image date and tesseract version (e.-g. `Scan to Paperless 2022-08-13 03:47:48, Tesseract 4.1.1`)
* Now we can extend a configuration with another. 
* The progress mode is improved
* The experimental mode is completely removes
* The near black and near white colors are set to black and white respectively, see `cut_black` and `cut_white` in the documentation

# Don't miss the documentation
- The environment variable present in the [README.md](https://github.com/sbrunner/scan-to-paperless/tree/master#scan-and-prepare-your-document-for-paperless#server-configuration).
- The [configuration](https://github.com/sbrunner/scan-to-paperless/blob/master/config.md) (and [process](https://github.com/sbrunner/scan-to-paperless/blob/master/process.md)) documentation.
- The full [changelog](https://github.com/sbrunner/scan-to-paperless/blob/master/CHANGELOG.md)
