### DISCUSSION TITLE
Scanner Source Issue

### DISCUSSION THREAD

**Discussion by DanielRiek** [sbrunner/scan-to-paperless#813] [General]
Hi,

I have an issue using your script, because my scanner does not understand the "--source ADF" command. Is there any way to change this without changing the code? Furthermore even when using --mode multi (resulting in omitting the source option) I get the following error from scanimage: `"scanimage: output is not a file, exiting"`

Options specific to device net:127.0.0.1:canon_dr:libusb:001:002':
  Standard:
    --source ADF Front|ADF Duplex [ADF Front]
        Selects the scan source (such as a document-feeder).
    --mode Lineart|Gray|Color [Gray]
        Selects the scan mode (e.g., lineart, monochrome, or color).
    --resolution 100|150|200|240|300|400|600dpi [600]
        Sets the resolution of the scanned image.
  Geometry:
    --page-width 0..215.872mm (in steps of 0.0211639) [215.872]
        Specifies the width of the media.  Required for automatic centering of
        sheet-fed scans.
    --page-height 0..355.554mm (in steps of 0.0211639) [279.364]
        Specifies the height of the media.
    -l 0..215.872mm (in steps of 0.0211639) [0]
        Top-left x position of scan area.
    -t 0..279.364mm (in steps of 0.0211639) [0]
        Top-left y position of scan area.
    -x 0..215.872mm (in steps of 0.0211639) [215.872]
        Width of scan-area.
    -y 0..279.364mm (in steps of 0.0211639) [279.364]
        Height of scan-area.
  Enhancement:
    --brightness -127..127 (in steps of 1) [0]
        Controls the brightness of the acquired image.
    --contrast -127..127 (in steps of 1) [0]
        Controls the contrast of the acquired image.
    --threshold 0..255 (in steps of 1) [inactive]
        Select minimum-brightness to get a white point
  Advanced:
    --df-thickness[=(yes|no)] [no]
        Detect double feeds using thickness sensor
    --df-length[=(yes|no)] [no]
        Detect double feeds by comparing document lengths
    --rollerdeskew[=(yes|no)] [no]
        Request scanner to correct skewed pages mechanically
    --swdeskew[=(yes|no)] [no]
        Request driver to rotate skewed pages digitally
    --swdespeck 0..9 (in steps of 1) [0]
        Maximum diameter of lone dots to remove from scan
    --swcrop[=(yes|no)] [no]
        Request driver to remove border from pages digitally
    --swskip 0..100% (in steps of 0.100006) [0]
        Request driver to discard pages with low percentage of dark pixels
    --stapledetect[=(yes|no)] [no]
        Request scanner to halt if stapled pages are detected
    --dropout-front None|Red|Green|Blue|Enhance Red|Enhance Green|Enhance Blue [None]
        One-pass scanners use only one color during gray or binary scanning,
        useful for colored paper or ink
    --dropout-back None|Red|Green|Blue|Enhance Red|Enhance Green|Enhance Blue [None]
        One-pass scanners use only one color during gray or binary scanning,
        useful for colored paper or ink
    --buffermode[=(yes|no)] [no]
        Request scanner to read pages async into internal memory
  Sensors:

**Comment by Joker45b** [comment]
I know you wrote without changing the code....  But my dirty fix was to edit the Line 130 in scan.py to:
`            scanimage += ["--source=Automatic Document Feeder"]`
Hope it helps

**Comment by sbrunner** [comment]
Or updating the `scanimage_arguments` in the configuration file

**Reply by mannp** [reply]
> Or updating the `scanimage_arguments` in the configuration file

@sbrunner I am finding this issue too, and I guess the question is, does editing the config work?

```
scan_folder: /home/local/Documents/paperless/scan 
scanimage_arguments: # Additional argument passed to the scanimage command
  - --device=fujitsu:ScanSnap S500M:1794
  - --source=ADF Duplex
  - --format=png
  - --mode=color
  - --resolution=300
default_args:
  auto_mask: {}
  auto_cut: {}
  run_pngquant: true
  cut_white: 200 # cut the near white color to have a uniform background
  dpi: 300 # Not necessary if the scanner generate a tiff file
  tesseract_lang: eng # The used languages for the OCR
```

This config, gives me the following command, line;

```
scanimage --device=fujitsu:ScanSnap S500M:1794 --source=ADF Duplex --format=png --mode=color --resolution=300 --batch=/home/local/Documents/paperless/scan/647779/source/image-%d.png --source=ADF
scanimage: setting of option --source failed (Invalid argument)
Command '['scanimage', '--device=fujitsu:ScanSnap S500M:1794', '--source=ADF Duplex', '--format=png', '--mode=color', '--resolution=300', '--batch=/home/local/Documents/paperless/scan/647779/source/image-%d.png', '--source=ADF']' returned non-zero exit status 1.
```

I wondered why  '--source=ADF' was always appended at the end, when it is not valid for my device. Wouldn't specifying a specific source in the config disable the appending of  '--source=ADF'?


```
Options specific to device `fujitsu:ScanSnap S500M:1794':
  Standard:
    --source ADF Front|ADF Back|ADF Duplex [ADF Front]
        Selects the scan source (such as a document-feeder).
```
Without the final '--source=ADF' this works.

scanimage, '--device=fujitsu:ScanSnap S500M:1794' '--source=ADF Front' '--format=png' '--mode=color' '--resolution=300' '--batch=/home/local/Documents/paperless/scan/671846/source/image-%d.png'

**Reply by sbrunner** [reply]
You should add in the config:
```yaml
modes:
  adf:
    scanimage_arguments:
      - --source=ADF
  double:
    scanimage_arguments:
      - --source=ADF
```

**Reply by mannp** [reply]
> ```yaml
> --source=ADF
> ```

--source=ADF is not valid for my scanner, so I have selected 'ADF Front', but that said scan keeps asking me to swap the paper over to scan the other side, when the scanner is capable of scanner both sides in one pass?

**Reply by sbrunner** [reply]
Oups wrong copy and paste :-)
=>
```yaml
modes:
  adf:
    scanimage_arguments: []
  double:
    scanimage_arguments: []
```

**Reply by mannp** [reply]
> Oups wrong copy and paste :-) =>
> 
> ```yaml
> modes:
>   adf:
>     scanimage_arguments: []
>   double:
>     scanimage_arguments: []
> ```

mmh

I actually changed to the following, which works;

```
modes:
  adf:
    scanimage_arguments:
      - --source=ADF Front
  double:
    scanimage_arguments:
      - --source=ADF Duplex
```

ADF Duplex does actually work fine 👍🏻
