### ISSUE TITLE
Exception in Finalise: KeyError: 'destination'

### ISSUE THREAD

**Issue by t0mcat1337** [sbrunner/scan-to-paperless#870]
Just stumbled across this promising project and give it a try.
I installed the client sides "scan" command as described, made this minimal config file in ~/.config/scan-to-paperless.yaml

```
scan_folder: /home/username/Paperless/scan/
scanimage_arguments: # Additional argument passed to the scanimage command
  - --device=escl:https://192.168.42.43:443
  - --format=png
  - --mode=color
  - --resolution=300
default_args:
  auto_mask: {}
  auto_cut: {}
  run_pngquant: true
  cut_white: 200 # cut the near white color to have a uniform background
  dpi: 300 # Not necessary if the scanner generate a tiff file
  tesseract_lang: de+eng # The used languages for the OCR
```
As having docker installed on the same machine (Ubuntu) already I fired up the docker container as described in the docs with this command (BTW: the argument is "--detach", not "--detatch" or simply -d ;) )

`docker run --name=scan-to-paperless --restart=unless-stopped --detach   --volume=/home/username/Paperless/scan:/source   --volume=/home/username/Paperless/consume:/destination   sbrunner/scan-to-paperless`

(The destination folder is at my local machine and not the real "consume" folder of paperless as I just wanted to test things out first)

After scanning the first image successfully the job was created in the "scan" folder. After removing "REMOVE_TO_CONTINUE" file the destination folder remains empty, the job folder remains as is. with "docker logs...." one can see this python exception:

```
Welcome to scanned images document to paperless.
Waiting...
/source/621178/config.yaml
Transform
tesseract /tmp/tmps39uh_jw.png - --psm 0 -l osd
Waiting...
/source/621178/config.yaml
Finalise
'destination'
Traceback (most recent call last):
  File "/opt/scan_to_paperless/process.py", line 1198, in main
    finalize(config, step, root_folder)
  File "/opt/scan_to_paperless/process.py", line 1050, in finalize
    destination = config["destination"]
  File "/usr/local/lib/python3.10/dist-packages/ruamel/yaml/comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'destination'

Waiting...
```

Am I assuming correctly there seems to be missing a "destination" key in the jobs config.yaml?
Indeed there is none and I can't find any "destination" entry in the "Full Config" description in the docs...

Any hint? Thx in advance
